Repository MESAHub/mesa, pull requests merged in 2024-07, with the labels that each got.

#665 chem: fix error handling of preprocessor
  chem/preprocessor/src/chem_support.f90
Labels: bug

#672 Chem/fix preprocessor error
  chem/preprocessor/chem_input_data.tar.xz
  chem/preprocessor/src/chem_support.f90
Labels: bug

#670 adding missing openmp directives and making python files (in linters/) python 3.12+ compatible
  atm/private/atm_utils.f90
  const/public/const_def.f90
  const/test/make/makefile_base
  const/test/src/test_const.f
  const/test/src/test_const.f90
  docs/source/known_bugs.rst
  docs/source/test_suite.rst
  linters/check_columns.py
  linters/check_defaults.py
  linters/check_empty_writes.py
  linters/check_omp_critical.py
  linters/check_photos.py
  linters/check_stop.py
  linters/fix_inlists.py
  linters/list_test_owner.py
  linters/mesa-linter.py
  linters/update_columns.py
  linters/update_ctrls.py
  mtx/private/bcyclic.f90
  mtx/public/mtx_solve_routines.inc
  scripts/stash.py
  star/private/star_bcyclic.f90
Labels: performance

#673 Minor improvements to parallelization
  mtx/public/mtx_solve_routines.inc
  star/private/star_bcyclic.f90
Labels: performance

#679 Typo fixes xingyzt
  docs/source/using_mesa/building_inlists.rst
  star/test_suite/12M_pre_ms_to_core_collapse/inlist_common
  star/test_suite/20M_pre_ms_to_core_collapse/inlist_common
  star/test_suite/hb_2M/README.rst
  star/test_suite/zams_to_cc_80/inlist_common
Labels: documentation

#685 removing redundant requirement in docs to build on readthedocs
  docs/requirements.txt
Labels: bug

#686 removing tag feature
  docs/requirements.txt
  docs/source/_tags/high-mass.rst
  docs/source/_tags/star.rst
  docs/source/_tags/tagsindex.rst
  star/test_suite/1.3M_ms_high_Z/README.rst
  star/test_suite/1.5M_with_diffusion/README.rst
  star/test_suite/conv_core_cpm/README.rst
  star/test_suite/high_mass/README.rst
Labels: bug

#687 remove tags in conf.py
  docs/source/conf.py
Labels: bug
