Repository MESAHub/mesa, pull requests merged in 2024-06, with the labels that each got.

#646 Automatic differentiation for cubic interpolation across type-1 and type-2 kap tables
  docs/source/changelog.rst
  docs/source/changelog_plots/cubic_dfridr_dkapdT.png
  docs/source/changelog_plots/cubic_dfridr_dkapdT_ad.png
  docs/source/changelog_plots/linear_dfridr_dkapdT.png
  interp_1d/make/makefile_base
  interp_1d/private/interp_1d_misc.f90
  interp_1d/private/interp_1d_mp_autodiff.f90
  interp_1d/private/interp_1d_pm_autodiff.f90
  interp_1d/public/interp_1d_lib.f90
  interp_1d/test/make/makefile_base
  interp_2d/make/makefile_base
  interp_2d/test/make/makefile_base
  kap/plotter/inlist_plotter
  kap/plotter/plotter.py
  kap/plotter/src/kap_plotter.f90
  kap/private/kap_eval_co.f90
  kap/private/kap_eval_fixed.f90
Labels: documentation, release-blocker, kap, autodiff

#659 adding copy button to docs
  docs/requirements.txt
  docs/source/conf.py
Labels: documentation

#664 adding python3 for jenkins to get Flatiron Jenkins build compiling again
  jenkins/Dockerfile
Labels: bug

#663 shmesa fix for issue #661
  scripts/shmesa/shmesa
Labels: bug

#649 adding pmocz as developer to docs / doc typos
  binary/test_suite/jdot_gr_check/README.rst
  binary/test_suite/jdot_ml_check/README.rst
  docs/source/about.rst
  docs/source/news/2016-06-19-r8845.rst
  docs/source/using_mesa/extending_mesa.rst
  docs/source/using_mesa/just_a_module.rst
  star/defaults/FORMAT
  star/test_suite/12M_pre_ms_to_core_collapse/README.rst
  star/test_suite/c13_pocket/README.rst
  star/test_suite/cburn_inward/README.rst
  star/test_suite/ccsn_IIp/README.rst
  star/test_suite/high_mass/README.rst
  star/test_suite/hse_riemann/README.rst
  star/test_suite/make_he_wd/README.rst
  star/test_suite/other_physics_hooks/README.rst
  star/test_suite/pisn/README.rst
  star/test_suite/ppisn/README.rst
  star/test_suite/split_burn_big_net/README.rst
  star/test_suite/test_memory/README.rst
  star/test_suite/timing/README.rst
  star/test_suite/twin_studies/README.rst
  star/test_suite/wd_c_core_ignition/README.rst
Labels: documentation, minor
