Repository MESAHub/mesa, pull requests merged in 2024-08, with the labels that each got.

#688 Updating starspot test_suite problem
  star/test_suite/conv_core_cpm/inlist_conv_core_cpm
  star/test_suite/starspots/README.rst
  star/test_suite/starspots/docs/hr_starspots_001496.svg
  star/test_suite/starspots/inlist_starspots
  star/test_suite/starspots/inlist_starspots_header
  star/test_suite/starspots/src/run_star_extras.f90
Labels: test_suite

#703 MESA-palooza updating plotting in test_suite
  docs/source/test_suite.rst
  star/test_suite/1.3M_ms_high_Z/README.rst
  star/test_suite/1.3M_ms_high_Z/inlist_pgstar
  star/test_suite/1.5M_with_diffusion/README.rst
  star/test_suite/7M_prems_to_AGB/README.rst
  star/test_suite/7M_prems_to_AGB/docs/hr000785.svg
  star/test_suite/7M_prems_to_AGB/inlist_7M_prems_to_AGB
  star/test_suite/7M_prems_to_AGB/inlist_7M_prems_to_AGB_header
  star/test_suite/7M_prems_to_AGB/inlist_pgstar
  star/test_suite/7M_prems_to_AGB/inlist_start
  star/test_suite/7M_prems_to_AGB/inlist_start_header
  star/test_suite/accreted_material_j/README.rst
  star/test_suite/accreted_material_j/docs/track1_000452.svg
  star/test_suite/accreted_material_j/history_columns.list
  star/test_suite/accreted_material_j/inlist_accreted_material_j
  star/test_suite/accreted_material_j/inlist_accreted_material_j_header
  star/test_suite/accreted_material_j/inlist_pgstar
  star/test_suite/accreted_material_j/inlist_zams
  star/test_suite/accreted_material_j/inlist_zams_header
  star/test_suite/conductive_flame/README.rst
  star/test_suite/conductive_flame/docs/grid1000597.png
  star/test_suite/conductive_flame/inlist_conductive_flame
  star/test_suite/conductive_flame/inlist_conductive_flame_header
  star/test_suite/conductive_flame/inlist_pgstar
  star/test_suite/conv_core_cpm/README.rst
  star/test_suite/diffusion_smoothness/README.rst
  star/test_suite/diffusion_smoothness/docs/brunt_000036.svg
  star/test_suite/diffusion_smoothness/inlist_diffusion_smoothness
  star/test_suite/diffusion_smoothness/inlist_diffusion_smoothness_header
  star/test_suite/diffusion_smoothness/inlist_zams
  star/test_suite/diffusion_smoothness/inlist_zams_header
  star/test_suite/each_test_run
  star/test_suite/high_mass/README.rst
  star/test_suite/high_mass/inlist_pgstar
  star/test_suite/make_zams/README.rst
  star/test_suite/make_zams/docs/grid_000192.svg
  star/test_suite/make_zams/inlist_zams
  star/test_suite/starspots/README.rst
  star/test_suite/wd_nova_burst/README.rst
  star/test_suite/wd_nova_burst/docs/wd_nova_burst_grid.svg
  star/test_suite/wd_nova_burst/inlist_pgstar
  star/test_suite/wd_nova_burst/inlist_setup
  star/test_suite/wd_nova_burst/inlist_setup_header
  star/test_suite/wd_nova_burst/inlist_wd_nova_burst
  star/test_suite/wd_nova_burst/inlist_wd_nova_burst_header
  star/test_suite/wd_nova_burst/plot.py
Labels: test_suite

#639 Prevent TDC with predictive mixing
  star/defaults/controls.defaults
  star/private/predictive_mix.f90
Labels: bug, release-blocker

#716 bugfix dP to d_P in create_initial_model
  star/private/create_initial_model.f90
Labels: bug

#721 [skip ci] fix and expand file_device and file_extension documentation
  star/defaults/pgstar.defaults
Labels: documentation
