Repository MESAHub/mesa, pull requests merged in 2025-02, with the labels that each got.

#782 Custom colors overhaul: test suite case
  star/test_suite/custom_colors/.gitignore
  star/test_suite/custom_colors/AType.params
  star/test_suite/custom_colors/BType.params
  star/test_suite/custom_colors/MDwarf.params
  star/test_suite/custom_colors/OType.params
  star/test_suite/custom_colors/PopII.params
  star/test_suite/custom_colors/PopIII.params
  star/test_suite/custom_colors/README.rst
  star/test_suite/custom_colors/compute_magnitudes
  star/test_suite/custom_colors/custom_colors_history_columns.list
  star/test_suite/custom_colors/data/blackbody_bc_v.txt
  star/test_suite/custom_colors/data/fake_av_maker.py
  star/test_suite/custom_colors/data/fake_av_v.txt
  star/test_suite/custom_colors/help
  star/test_suite/custom_colors/history_columns.list
  star/test_suite/custom_colors/inlist
  star/test_suite/custom_colors/inlist_1.0
  star/test_suite/custom_colors/inlist_template/AType.params
  star/test_suite/custom_colors/inlist_template/BType.params
  star/test_suite/custom_colors/inlist_template/MDwarf.params
  star/test_suite/custom_colors/inlist_template/OType.params
  star/test_suite/custom_colors/inlist_template/PopII.params
  star/test_suite/custom_colors/inlist_template/PopIII.params
  star/test_suite/custom_colors/mk
  star/test_suite/custom_colors/python_helpers/HISTORY_check.py
  star/test_suite/custom_colors/python_helpers/SED_check.py
  star/test_suite/custom_colors/python_helpers/batch_run.py
  star/test_suite/custom_colors/python_helpers/plothistory.py
  star/test_suite/custom_colors/python_helpers/python_custom_colours/calculate_absolute_mags.py
  star/test_suite/custom_colors/python_helpers/python_custom_colours/compute_mags.py
  star/test_suite/custom_colors/python_helpers/python_custom_colours/compute_mags_n.py
  star/test_suite/custom_colors/python_helpers/python_custom_colours/conv_filt.py
  star/test_suite/custom_colors/python_helpers/python_custom_colours/convolve_filters.py
  star/test_suite/custom_colors/python_helpers/python_custom_colours/generalblackbody.py
  star/test_suite/custom_colors/python_helpers/svo/svo_filter_grabber.py
  star/test_suite/custom_colors/python_helpers/svo/svo_regen_spectra_lookup.py
  star/test_suite/custom_colors/python_helpers/svo/svo_spectra_filter.py
  star/test_suite/custom_colors/python_helpers/svo/svo_spectra_grabber.py
  star/test_suite/custom_colors/src/oldrun_star_extras.f90.txt
  star/test_suite/custom_colors/src/photometric_run_star_extras.f90
  star/test_suite/custom_colors/src/run.f90
  star/test_suite/custom_colors/src/run_star_extras.f90
  star/test_suite/custom_colors/src/sed_check.py
  star/test_suite/custom_colors/src/sed_check.txt
  star/test_suite/custom_colors/src/spectra_run_star_extras.f90
  star/test_suite/custom_colors/test_file
Labels: test_suite, colors

#778 adjust delta_Pg
  docs/source/changelog.rst
  star/defaults/controls.defaults
  star/private/ctrls_io.f90
  star/private/report.f90
  star/private/star_utils.f90
  star_data/private/star_controls.inc
Labels: enhancement, release-blocker

#785 fixing some missing d0's
  atm/private/atm_t_tau_relations.f90
  atm/private/atm_t_tau_uniform.f90
  atm/private/atm_t_tau_varying.f90
  atm/test/src/test_atm_support.f90
  atm/test/test_output
  ionization/private/ion_table_plot.f90
  ionization/private/ion_tables_eval.f90
  ionization/test/src/test_ionization_support.f90
  star/dev_cases_test_TDC/dev_TDC_through_ppisn/src/run_star_extras.f90
  star/test_suite/R_CrB_star/src/run_star_extras.f90
  star/test_suite/c13_pocket/src/run_star_extras.f90
  star/test_suite/cburn_inward/src/run_star_extras.f90
  star/test_suite/ccsn_IIp/src/run_star_extras.f90
  star/test_suite/conductive_flame/src/run_star_extras.f90
  star/test_suite/pisn/src/run_star_extras.f90
  star/test_suite/ppisn/src/run_star_extras.f90
  star/test_suite/radiative_levitation/src/run_star_extras.f90
  star/test_suite/rsp_BEP/src/run_star_extras.f90
  star/test_suite/rsp_BLAP/src/run_star_extras.f90
  star/test_suite/rsp_Cepheid/src/run_star_extras.f90
  star/test_suite/rsp_Cepheid_6M/src/run_star_extras.f90
  star/test_suite/rsp_Delta_Scuti/src/run_star_extras.f90
  star/test_suite/rsp_Type_II_Cepheid/src/run_star_extras.f90
  star/test_suite/simplex_solar_calibration/src/simplex_search_run_support.f90
  stella/src/util/gnufor2.f90
Labels: bug
